### ISSUE TITLE
Update translation of description for all the languages.

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#152]
Currently we just have:
```
description:
  en: Lessons about the Elixir programming language
  jp: Lessons about the Elixir programming language
  cn: Lessons about the Elixir programming language
  es: Lessons about the Elixir programming language
  pt: Lições sobre a linguagem de programação Elixir
  vi: Lessons about the Elixir programming language
  ru: Lessons about the Elixir programming language
```
## Roadmap:
- [x] en
- [x] jp
- [x] cn
- [x] es
- [x] pt
- [x] vi
- [x] ru
- [x] sk
